"""Subclass of DialogManageArduinos, which is generated by wxFormBuilder."""

import wx
import gui
import lib.serialArduinoUtils

# Implementing DialogManageArduinos
class XPArduinoDialogManageArduinos( gui.DialogManageArduinos ):
	
	def __init__(self,parent):
		#initialize parent class
		gui.DialogManageArduinos.__init__(self,parent)
		self.arduinoListCtrl.AppendToggleColumn("Select",wx.dataview.DATAVIEW_CELL_ACTIVATABLE, 50, wx.ALIGN_CENTER_HORIZONTAL) 
		self.arduinoListCtrl.AppendTextColumn("Port", wx.dataview.DATAVIEW_CELL_INERT, 50) 
		self.arduinoListCtrl.AppendTextColumn("Name", wx.dataview.DATAVIEW_CELL_EDITABLE, 100) 
		self.arduinoListCtrl.AppendTextColumn("Description", wx.dataview.DATAVIEW_CELL_INERT, 180)
		self.arduinoListCtrl.AppendTextColumn("Serial Number", wx.dataview.DATAVIEW_CELL_INERT, 140)
		self.arduinoListCtrl.AppendTextColumn("Manufacturer", wx.dataview.DATAVIEW_CELL_INERT, 150)
		
	def refreshArduinoList(self):
		self.arduinoListCtrl.DeleteAllItems()
		list = lib.serialArduinoUtils.listArduinosSerial()
		index = 0
		for p in list:
			description = str(p.description)
			if "Ard" in description:
				print("FOOUND ARDUINO")
				serial_number = str(p.serial_number)
				if serial_number in self.GetParent().arduinoDict:  # only display the arduino if it is not already in our list
					pass
				else:
					data = [False, str(p.device),"NAME"+str(index), description, str(p.serial_number), str(p.manufacturer)]
					self.arduinoListCtrl.AppendItem(data)
								
				index = index + 1
			print (p.description,  p.serial_number, p.hwid, p.vid, p.pid, p.manufacturer)
	
	def onApplyClicked(self, event):
		ArdtreeDataControl = self.GetParent().Arduino_dataViewTreeCtrl

		for i in range(0,self.arduinoListCtrl.GetItemCount()):
			if self.arduinoListCtrl.GetToggleValue(i,0) == True:
				
				self.GetParent().arduinoDict[self.arduinoListCtrl.GetTextValue(i, 4)]= {'Port': 		self.arduinoListCtrl.GetTextValue(i, 1) ,
																						'Name': 		self.arduinoListCtrl.GetTextValue(i, 2),
																						'Description': 	self.arduinoListCtrl.GetTextValue(i, 3),
																						'Manufacturer': self.arduinoListCtrl.GetTextValue(i, 5)}
		self.GetParent().refreshArduinoTree()
		self.EndModal(0)
		
