# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1213, 752)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(0, 0))
        self.splitter.setBaseSize(QtCore.QSize(0, 0))
        self.splitter.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.splitter.setAutoFillBackground(False)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(100, 400))
        self.widget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget.setBaseSize(QtCore.QSize(0, 0))
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.arduinoTreeWidget = QtWidgets.QTreeWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arduinoTreeWidget.sizePolicy().hasHeightForWidth())
        self.arduinoTreeWidget.setSizePolicy(sizePolicy)
        self.arduinoTreeWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.arduinoTreeWidget.setBaseSize(QtCore.QSize(0, 0))
        self.arduinoTreeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.arduinoTreeWidget.setColumnCount(2)
        self.arduinoTreeWidget.setObjectName("arduinoTreeWidget")
        self.horizontalLayout_2.addWidget(self.arduinoTreeWidget)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setMinimumSize(QtCore.QSize(500, 0))
        self.widget1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.arduinoEditForm = QtWidgets.QWidget(self.widget1)
        self.arduinoEditForm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.arduinoEditForm.setObjectName("arduinoEditForm")
        self.formLayout = QtWidgets.QFormLayout(self.arduinoEditForm)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.arduinoEditForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("color: white;\n"
"background: rgb(0, 151, 157);\n"
"padding: 3px\n"
"\n"
"")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_7)
        self.label = QtWidgets.QLabel(self.arduinoEditForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.ardNameLineEdit = QtWidgets.QLineEdit(self.arduinoEditForm)
        self.ardNameLineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.ardNameLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ardNameLineEdit.setObjectName("ardNameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ardNameLineEdit)
        self.label_4 = QtWidgets.QLabel(self.arduinoEditForm)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.ardPortLineEdit = QtWidgets.QLineEdit(self.arduinoEditForm)
        self.ardPortLineEdit.setEnabled(False)
        self.ardPortLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ardPortLineEdit.setReadOnly(True)
        self.ardPortLineEdit.setObjectName("ardPortLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ardPortLineEdit)
        self.label_5 = QtWidgets.QLabel(self.arduinoEditForm)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.ardSerialNrLineEdit = QtWidgets.QLineEdit(self.arduinoEditForm)
        self.ardSerialNrLineEdit.setEnabled(False)
        self.ardSerialNrLineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.ardSerialNrLineEdit.setReadOnly(True)
        self.ardSerialNrLineEdit.setObjectName("ardSerialNrLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.ardSerialNrLineEdit)
        self.label_2 = QtWidgets.QLabel(self.arduinoEditForm)
        self.label_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ardDescriptionLineEdit = QtWidgets.QLineEdit(self.arduinoEditForm)
        self.ardDescriptionLineEdit.setEnabled(False)
        self.ardDescriptionLineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.ardDescriptionLineEdit.setBaseSize(QtCore.QSize(0, 0))
        self.ardDescriptionLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ardDescriptionLineEdit.setReadOnly(True)
        self.ardDescriptionLineEdit.setObjectName("ardDescriptionLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.ardDescriptionLineEdit)
        self.label_6 = QtWidgets.QLabel(self.arduinoEditForm)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.ardManufacturerLineEdit = QtWidgets.QLineEdit(self.arduinoEditForm)
        self.ardManufacturerLineEdit.setEnabled(False)
        self.ardManufacturerLineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.ardManufacturerLineEdit.setFrame(True)
        self.ardManufacturerLineEdit.setReadOnly(True)
        self.ardManufacturerLineEdit.setObjectName("ardManufacturerLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.ardManufacturerLineEdit)
        self.horizontalLayout_3.addWidget(self.arduinoEditForm)
        self.switchEditForm = QtWidgets.QWidget(self.widget1)
        self.switchEditForm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.switchEditForm.setObjectName("switchEditForm")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.switchEditForm)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_17 = QtWidgets.QLabel(self.switchEditForm)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.switchEditForm)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 8, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.switchEditForm)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 8, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.switchEditForm)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 7, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 13, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.switchEditForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.switchEditForm)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 8, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.switchEditForm)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 8, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.switchEditForm)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 12, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.switchEditForm)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 2, 1, 1)
        self.SWOFF_XPCMD_comboBox = QtWidgets.QComboBox(self.switchEditForm)
        self.SWOFF_XPCMD_comboBox.setObjectName("SWOFF_XPCMD_comboBox")
        self.gridLayout_2.addWidget(self.SWOFF_XPCMD_comboBox, 11, 2, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.switchEditForm)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 12, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.switchEditForm)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.switchEditForm)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 12, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.switchEditForm)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 11, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.switchEditForm)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 10, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 9, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.switchEditForm)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 12, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.switchEditForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: white;\n"
"background: rgb(0, 151, 157);\n"
"padding: 3px\n"
"")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 1, 1, 4)
        self.SWON_XPCMD_comboBox = QtWidgets.QComboBox(self.switchEditForm)
        self.SWON_XPCMD_comboBox.setEditable(True)
        self.SWON_XPCMD_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.SWON_XPCMD_comboBox.setObjectName("SWON_XPCMD_comboBox")
        self.gridLayout_2.addWidget(self.SWON_XPCMD_comboBox, 7, 2, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.switchEditForm)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 3, 1, 1, 1)
        self.SW_PIN_comboBox = QtWidgets.QComboBox(self.switchEditForm)
        self.SW_PIN_comboBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.SW_PIN_comboBox.setObjectName("SW_PIN_comboBox")
        self.gridLayout_2.addWidget(self.SW_PIN_comboBox, 3, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.switchEditForm)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 2, 1, 2)
        self.horizontalLayout_3.addWidget(self.switchEditForm)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1213, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuArduino = QtWidgets.QMenu(self.menubar)
        self.menuArduino.setObjectName("menuArduino")
        self.menuX_Plane = QtWidgets.QMenu(self.menubar)
        self.menuX_Plane.setObjectName("menuX_Plane")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAdd_Arduino = QtWidgets.QAction(MainWindow)
        self.actionAdd_Arduino.setObjectName("actionAdd_Arduino")
        self.actionUDP_Settings = QtWidgets.QAction(MainWindow)
        self.actionUDP_Settings.setObjectName("actionUDP_Settings")
        self.actionAdd_component = QtWidgets.QAction(MainWindow)
        self.actionAdd_component.setObjectName("actionAdd_component")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menuArduino.addAction(self.actionAdd_Arduino)
        self.menuArduino.addAction(self.actionAdd_component)
        self.menuX_Plane.addAction(self.actionUDP_Settings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuArduino.menuAction())
        self.menubar.addAction(self.menuX_Plane.menuAction())

        self.retranslateUi(MainWindow)
        self.arduinoTreeWidget.customContextMenuRequested['QPoint'].connect(MainWindow.ardTreeContextMenuRequested)
        self.actionQuit.triggered.connect(MainWindow.close)
        self.actionSave.triggered.connect(MainWindow.saveToXML)
        self.actionAdd_Arduino.triggered.connect(MainWindow.pickArduino)
        self.arduinoTreeWidget.itemSelectionChanged.connect(MainWindow.ardTreeSelectionChanged)
        self.ardNameLineEdit.editingFinished.connect(MainWindow.ardEditingFinished)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.arduinoTreeWidget.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.arduinoTreeWidget.headerItem().setText(1, _translate("MainWindow", "Serial nr"))
        self.label_7.setText(_translate("MainWindow", "Edit Arduino Settings"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Port"))
        self.label_5.setText(_translate("MainWindow", "Serial Number  "))
        self.label_2.setText(_translate("MainWindow", "Description"))
        self.label_6.setText(_translate("MainWindow", "Manufacturer"))
        self.label_17.setText(_translate("MainWindow", "State"))
        self.label_13.setText(_translate("MainWindow", "to value: "))
        self.label_10.setText(_translate("MainWindow", "Send XPlane Command: "))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_11.setText(_translate("MainWindow", "Set Dataref: "))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label_16.setText(_translate("MainWindow", "to value:"))
        self.label_9.setText(_translate("MainWindow", "Switch ON actions:"))
        self.label_12.setText(_translate("MainWindow", "Send XPlane Command: "))
        self.label_15.setText(_translate("MainWindow", "Switch OFF actions"))
        self.label_14.setText(_translate("MainWindow", "Set Dataref:"))
        self.label_8.setText(_translate("MainWindow", "Edit switch"))
        self.label_18.setText(_translate("MainWindow", "Arduino pin:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuArduino.setTitle(_translate("MainWindow", "Arduino"))
        self.menuX_Plane.setTitle(_translate("MainWindow", "X Plane"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAdd_Arduino.setText(_translate("MainWindow", "Add Arduino"))
        self.actionUDP_Settings.setText(_translate("MainWindow", "UDP Settings"))
        self.actionAdd_component.setText(_translate("MainWindow", "Add component"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

