[Graphics]
Fullscreen = False
MonitorID = 0
; choose the monitor we will run on if in fullscreen 0 = first monitor, 1 = second monitor and so on

BgdColor_R = 0.35
BgdColor_B = 0.35
BgdColor_G = 0.35
ScreenWidth = 1440
ScreenHeight = 900
BufferSwapInterval = 1
; recommend 1. 0 will let the game run as fast as it can. Else specify minimum number of monitor refreshes the driver wait before swapping the buffers. Must be an integer, 1 should be 60FPS, 2 30FPS and so on

